server:
    port: ${port:8001}
spring:
  datasource:
    url: jdbc:h2:~/uploaddb
    driver-class: org.h2.Driver
    username: sa
    password:
    jpa:
      show-sql: false
      repositories:
         enabled: true
app:
  upload:
    chunk:
      size: 10
    destdir:
security:
  user:
    name: admin
    password: 78fa095d-3f4c-48b1-ad50-e24c31d5cf35
  basic:
    enabled: true
#zuul:
#  routes:
#    resource:
#      path: /icd/**
#      url: http://localhost:8080
